### ISSUE TITLE
Thrusters are not applying force

### ISSUE THREAD

**Issue by 19PHOBOSS98** [SuperCraftAlex/VS_tournament_continued#1]
![2023-06-22_16 44 58](https://github.com/SuperCraftAlex/VS_tournament_continued/assets/37253663/b6668ad1-b1e4-4f31-bed9-c46ec8afb9e2)
Thrusters are not applying force. I tried fully upgrading it to level 5 and set the configured thruster speed to 55000. It still wasn't able to push this wool craft an inch on max redstone power.

**Comment by SuperCraftAlex** [comment]
Im sure your not that dumb but i will ask it anyways: you made sure its a ship right?

if yes then i dont understand my life anymore
hmmmmmmm
oh
mh

**Comment by SuperCraftAlex** [comment]
fixed
